folder: "/home/xianyi/Research/MCTS/general_planner/batch_test"

number_of_experiments: 10
visualize_option: setup # setup, show, none. (overwrite visualize_option in setup.yaml)

collect_results: true

sample_start_and_goal:
  random: true
  position_upper_bound: [2,2,0.5]
  position_lower_bound: [-2,-2,0.5]